//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORICO_INVENTARIO_BAJAS
    {
        public int id_historico { get; set; }
        public int id_empleado { get; set; }
        public int id_inventario_historico { get; set; }
        public System.DateTime fecha { get; set; }
        public string descripcion { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        public virtual INVENTARIO_BAJAS INVENTARIO_BAJAS { get; set; }
    }
}
