//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORICO
    {
        public int id_historico { get; set; }
        public int id_usuario_historico { get; set; }
        public int id_solicitud_historico { get; set; }
        public string descripcion_historico { get; set; }
    
        public virtual SOLICITUD SOLICITUD { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
