//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO_BAJAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INVENTARIO_BAJAS()
        {
            this.HISTORICO_INVENTARIO_BAJAS = new HashSet<HISTORICO_INVENTARIO_BAJAS>();
        }
    
        public int id_inventario_bajas { get; set; }
        public int id_producto_inventario { get; set; }
        public int cantidad_existencias { get; set; }
        public System.DateTime fecha_actualizacion_inventario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORICO_INVENTARIO_BAJAS> HISTORICO_INVENTARIO_BAJAS { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
