//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO_ELEMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICIO_ELEMENTO()
        {
            this.SOLICITUD = new HashSet<SOLICITUD>();
        }
    
        public int id_servicio_elemento { get; set; }
        public int id_servicio { get; set; }
        public Nullable<int> id_elemento { get; set; }
        public Nullable<decimal> precio { get; set; }
    
        public virtual ELEMENTO ELEMENTO { get; set; }
        public virtual SERVICIO SERVICIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUD> SOLICITUD { get; set; }
    }
}
