//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOLICITUD()
        {
            this.DETALLE_FACTURA_SOLICITUD = new HashSet<DETALLE_FACTURA_SOLICITUD>();
            this.ESCALADO = new HashSet<ESCALADO>();
            this.HISTORICO_SOLICITUD = new HashSet<HISTORICO_SOLICITUD>();
        }
    
        public int id_solicitud { get; set; }
        public int id_prioridad_solicitud { get; set; }
        public int id_estado_solicitud { get; set; }
        public int id_usuario_solicitud { get; set; }
        public int id_servicio_solicitud { get; set; }
        public Nullable<int> id_elemento_solicitud { get; set; }
        public Nullable<System.DateTime> fecha_solicitud { get; set; }
        public string descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_FACTURA_SOLICITUD> DETALLE_FACTURA_SOLICITUD { get; set; }
        public virtual ELEMENTO ELEMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESCALADO> ESCALADO { get; set; }
        public virtual ESTADO_SOLICITUD ESTADO_SOLICITUD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORICO_SOLICITUD> HISTORICO_SOLICITUD { get; set; }
        public virtual PRIORIDAD PRIORIDAD { get; set; }
        public virtual SERVICIO SERVICIO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
