//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosDigitalesProy.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TELEFONO_USUARIO
    {
        public int id_telefono { get; set; }
        public int id_usuario_telefono { get; set; }
        public string numero_telefono { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
